query some {
  select(query: "a") {
    node
    attr(name: "href")
    classList
    class: attr(name: "class")
  }
  home: select(query: ".home") {
    node
    link: select(query: "a") {
      node
      href: attr(name: "href")
      text
      class: attr(name: "class")
    }
  }
  nav: select(query: "#nav") {
    node
    link: select(query: "a") {
      href: attr(name: "href")
      text
    }
  }
}
