scalar HTMLElement
directive @trim on FIELD
directive @number on FIELD
directive @replace(
  search: String
  replacement: String = ""
  flags: String = ""
) on FIELD
type Node {
  node: HTMLElement
  text: String
  html: String
  classList: [String]
  attr(name: String!): String
  select(selector: String): Node
  parent: Node
  attributes: AttributesMap
  next: Node
  selectAll(selector: String): [Node!]
  childNodes: [Node!]
  click(selector: String): Document
  scrollIntoView: Document
}
scalar AttributesMap
type Document {
  title: String
  referrer: String
  select(selector: String): Node
  selectAll(selector: String): [Node!]
}
type Query {
  select(selector: String): Node
  selectAll(selector: String): [Node!]
  document(background: Boolean): Document
}
