scalar HTMLElement
scalar JSON
scalar AttributesMap

directive @trim on FIELD
directive @number on FIELD
directive @replace(
  search: String
  replacement: String = ""
  flags: String = ""
) on FIELD

type Query {
  echo(
    json: JSON
    array: [JSON]
    parse: String
    string: String
    number: Float
    boolean: Boolean
  ): JSON
  select(selector: String): Node
  selectAll(selector: String): [Node!]
  document(location: String, waitForSelector: String): Document
}

type Document {
  echo(
    json: JSON
    array: [JSON]
    parse: String
    string: String
    number: Float
    boolean: Boolean
  ): JSON
  title: String
  referrer: String
  location: String
  select(selector: String): Node
  selectAll(selector: String): [Node!]
}

type Node {
  echo(
    json: JSON
    array: [JSON]
    parse: String
    string: String
    number: Float
    boolean: Boolean
  ): JSON
  node: HTMLElement
  text: String
  innerText: String
  html: String
  classList: [String]
  attr(name: String!): String
  select(selector: String): Node
  parent: Node
  attributes: AttributesMap
  next: Node
  selectAll(selector: String): [Node!]
  childNodes: [Node!]
  click(selector: String, waitForSelector: String): Node
  root: Node
  scrollIntoView: Document
}
